behaviors:
  Movement:
    trainer_type: ppo

    hyperparameters:
      batch_size: 64  # Number of experiences used for each training step
      buffer_size: 2048 # Number of experiences collected before updating the model
      learning_rate: 3.0e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: true
      hidden_units: 128
      num_layers: 2  # Number of layers in the neural network
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper  # Helps with goal-based learning
      deterministic: false

    reward_signals:
      extrinsic:
       gamma: 0.99
       strength: 1.0

    max_steps: 500000 # Total number of training steps before stopping
    time_horizon: 64  # How long the agent remembers experiences
    summary_freq: 10000  # How often data is logged for TensorBoard
    keep_checkpoints: 5  # Number of model checkpoints to save
    checkpoint_interval: 500000 # Every 500000 steps save a checkpoint
    threaded: false
