behaviors:
  Movement:
    trainer_type: ppo

    hyperparameters:
      batch_size: 512  # Number of experiences used for each training step
      buffer_size: 4096 # Number of experiences collected before updating the model
      learning_rate: 2.5e-4
      beta: 5.0e-3
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3

    network_settings:
      normalize: true
      hidden_units: 256
      num_layers: 3  # Number of layers in the neural network
      vis_encode_type: simple
      memory: null
      goal_conditioning_type: hyper  # Helps with goal-based learning
      deterministic: false

    reward_signals:
      extrinsic:
       gamma: 0.99
       strength: 1.0

    curiosity:  # Enables curiosity-driven learning
        strength: 0.02
        gamma: 0.99

    max_steps: 5000000  # Total number of training steps before stopping
    time_horizon: 128  # How long the agent remembers experiences
    summary_freq: 1000000
    keep_checkpoints: 5  # Number of model checkpoints to save
    checkpoint_interval: 200000
    threaded: false
